load("@rules_python//python:pip.bzl", "compile_pip_requirements")
load("@rules_python//python:py_test.bzl", "py_test")

compile_pip_requirements(
    name = "requirements",
    src = "requirements.in",
    requirements_txt = "requirements_lock.txt",
)

py_test(
    name = "py_spy_test",
    srcs = ["py_spy_test.py"],
    deps = ["@pypi//py_spy:pkg"],
)
