services:
  bazel-dev:
    build: .
    working_dir: /app/examples/site-packages
    stdin_open: true
    tty: true
    volumes:
      - ../..:/app
      - ./.cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
